# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 606617be5c57cf06c61fa85fdf37565a1ff58e33537cb158040e9ad2d87d76b5898751a3aee5d14dd0f639c546b5924651fa8d537607a891d263ae5067f4acba

test:
  secret_key_base: 8f1c8bfb010ebbeafd9f9de45526eb9527d2fc5e183c82e7660b6e88944e65a69f84cbe4bead62a074ae77524575c2174611272fb3edd94df1eac7454ba6dc62

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
